services:
  - type: web
    name: portfolio
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn portfolio_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
