# Generated by Django 6.0.3 on 2026-03-21 15:35

import datetime

from django.db import migrations, models


def seed_portfolio_data(apps, schema_editor):
    Profile = apps.get_model('portfolio', 'Profile')
    Skill = apps.get_model('portfolio', 'Skill')
    Project = apps.get_model('portfolio', 'Project')
    Certificate = apps.get_model('portfolio', 'Certificate')

    Profile.objects.create(
        full_name='Vishnu',
        headline='Django Developer | Problem Solver',
        short_intro='I build practical web applications with clean backend architecture and user-friendly interfaces.',
        about_me='I am passionate about Python and web development. I enjoy building projects that solve real problems and improve user experience.',
        email='your.email@example.com',
        phone='+91-0000000000',
        location='India',
        linkedin_url='https://www.linkedin.com/',
        github_url='https://github.com/',
        resume_url='https://example.com/resume.pdf',
    )

    Skill.objects.bulk_create([
        Skill(name='Python', skill_type='technical', proficiency=90, display_order=1),
        Skill(name='Django', skill_type='technical', proficiency=88, display_order=2),
        Skill(name='HTML/CSS', skill_type='technical', proficiency=85, display_order=3),
        Skill(name='SQL', skill_type='technical', proficiency=82, display_order=4),
        Skill(name='Communication', skill_type='soft', proficiency=87, display_order=1),
        Skill(name='Teamwork', skill_type='soft', proficiency=86, display_order=2),
        Skill(name='Problem Solving', skill_type='soft', proficiency=90, display_order=3),
    ])

    Project.objects.bulk_create([
        Project(
            title='Student Management System',
            description='A Django-based CRUD platform to manage student records, attendance, and reports.',
            technologies='Django, SQLite, HTML, CSS, Bootstrap',
            github_url='https://github.com/example/student-management',
            live_url='',
            is_featured=True,
            completed_on=datetime.date(2025, 10, 10),
            display_order=1,
        ),
        Project(
            title='Personal Portfolio Website',
            description='A responsive portfolio website to showcase profile, projects, and certifications with a contact form.',
            technologies='Django, HTML, CSS',
            github_url='https://github.com/example/portfolio',
            live_url='',
            is_featured=True,
            completed_on=datetime.date(2026, 2, 5),
            display_order=2,
        ),
    ])

    Certificate.objects.bulk_create([
        Certificate(
            title='Python for Everybody',
            issuer='Coursera',
            issue_date=datetime.date(2025, 6, 15),
            credential_id='COURSE-12345',
            credential_url='https://www.coursera.org/',
            display_order=1,
        ),
        Certificate(
            title='Django Web Development',
            issuer='Udemy',
            issue_date=datetime.date(2025, 9, 20),
            credential_id='UDEMY-67890',
            credential_url='https://www.udemy.com/',
            display_order=2,
        ),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('issuer', models.CharField(max_length=120)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-issue_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('headline', models.CharField(max_length=200)),
                ('short_intro', models.TextField()),
                ('about_me', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('resume_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=240)),
                ('image_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-completed_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('skill_type', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft')], default='technical', max_length=20)),
                ('proficiency', models.PositiveSmallIntegerField(default=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RunPython(seed_portfolio_data, migrations.RunPython.noop),
    ]
