# Generated by Django 6.0.3 on 2026-03-22 17:04

from django.db import migrations, models


def seed_default_skills(apps, schema_editor):
    Skill = apps.get_model("portfolio", "Skill")

    default_skills = [
        ("C", "programming_languages", 0),
        ("C++", "programming_languages", 1),
        ("Java", "programming_languages", 2),
        ("Python", "programming_languages", 3),
        ("JavaScript", "programming_languages", 4),
        ("Django", "frameworks_libraries", 0),
        ("Flask", "frameworks_libraries", 1),
        ("Bootstrap", "frameworks_libraries", 2),
        ("React (Basics)", "frameworks_libraries", 3),
        ("Git", "tools", 0),
        ("VS Code", "tools", 1),
        ("Linux", "tools", 2),
        ("Postman", "tools", 3),
        ("MySQL", "databases", 0),
        ("PostgreSQL", "databases", 1),
        ("SQLite", "databases", 2),
    ]

    for name, category, display_order in default_skills:
        Skill.objects.get_or_create(
            name=name,
            defaults={
                "category": category,
                "skill_type": "technical",
                "proficiency": 80,
                "display_order": display_order,
            },
        )


def unseed_default_skills(apps, schema_editor):
    Skill = apps.get_model("portfolio", "Skill")
    names_to_remove = [
        "C",
        "C++",
        "Java",
        "Python",
        "JavaScript",
        "Django",
        "Flask",
        "Bootstrap",
        "React (Basics)",
        "Git",
        "VS Code",
        "Linux",
        "Postman",
        "MySQL",
        "PostgreSQL",
        "SQLite",
    ]
    Skill.objects.filter(name__in=names_to_remove).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certificate_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming_languages', 'Programming Languages'), ('frameworks_libraries', 'Frameworks/Libraries'), ('tools', 'Tools'), ('databases', 'Databases'), ('soft', 'Soft Skills')], default='programming_languages', max_length=40),
        ),
        migrations.RunPython(seed_default_skills, unseed_default_skills),
    ]
